---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
        - name: app
          # Make sure to update this property, and use your own Docker image.
          image: app:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
          ports:
            - name: http
              containerPort: 8080
          # We use a LivenessProbe and a ReadinessProbe to mark this pod
          # as ready as soon as the app is actually running.
          # Using these K8s features, network traffic will not be sent to this app
          # until this endpoint returns a 200 OK response.
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            initialDelaySeconds: 20
            failureThreshold: 20
            periodSeconds: 1
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            failureThreshold: 2
            periodSeconds: 1
          env:
            # Read the ConfigMap mounted as a volume under /etc/config.
            - name: SPRING_CONFIG_IMPORT
              value: configtree:/etc/config/
          volumeMounts:
            - mountPath: /etc/config
              name: config
        - name: opa
          image: openpolicyagent/opa:0.60.0
          ports:
            - name: http
              containerPort: 8181
          args:
            - "run"
            - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
            - "--server"
            - "/policies"
          volumeMounts:
            - readOnly: true
              mountPath: /policies
              name: example-policy
          livenessProbe:
            httpGet:
              scheme: HTTP              # assumes OPA listens on localhost:8181
              port: 8181
            initialDelaySeconds: 5      # tune these periods for your environemnt
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: config
        - name: example-policy
          configMap:
            name: example-policy
